<a href="https://colab.research.google.com/github/nexusFour2026/test/blob/main/Task2(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving dataset-2.csv to dataset-2.csv

In [3]:
import pandas as pd
df = pd.read_csv("dataset-2.csv")

df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,BMW,M235 i,2015,"81,000 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,White,Red,None reported,Yes,"$27,890"
1,BMW,750 i,2017,"24,650 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes,"$50,000"
2,Aston,Martin V8 Vantage Base,2008,"62,378 mi.",Gasoline,380.0HP 4.3L 8 Cylinder Engine Gasoline Fuel,M/T,Red,Beige,At least 1 accident or damage reported,Yes,"$33,995"
3,INFINITI,QX80 Luxe,2022,"49,860 mi.",Gasoline,5.6L V8 32V GDI DOHC,Automatic,Black Obsidian,Graphite,At least 1 accident or damage reported,Yes,"$47,645"
4,Subaru,BRZ Premium,2023,"5,800 mi.",Gasoline,228.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,Black,None reported,Yes,"$29,990"

In [4]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       126
engine            0
transmission      0
ext_col           0
int_col           0
accident         92
clean_title     479
price             0
dtype: int64

In [9]:
df["clean_title"] = df["clean_title"].fillna(df["clean_title"].mode())

In [10]:
df["accident"] = df["accident"].fillna(df["accident"].mode()[0])

In [11]:
df["fuel_type"] = df["fuel_type"].fillna(df["fuel_type"].mode()[0])

In [12]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type         0
engine            0
transmission      0
ext_col           0
int_col           0
accident          0
clean_title     479
price             0
dtype: int64

In [14]:
df["clean_title"] = df["clean_title"].fillna(df["clean_title"].mode(0))

In [15]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type         0
engine            0
transmission      0
ext_col           0
int_col           0
accident          0
clean_title     479
price             0
dtype: int64

In [16]:
df["clean_title"] = df["clean_title"].fillna(df["clean_title"].mode()[0])

In [17]:
df.isnull().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["brand"].unique()

array(['BMW', 'Aston', 'INFINITI', 'Subaru', 'Mercedes-Benz', 'RAM',
       'Mazda', 'Lexus', 'Porsche', 'Alfa', 'Dodge', 'Maserati',
       'Chrysler', 'Cadillac', 'Mitsubishi', 'Ford', 'MINI', 'Chevrolet',
       'Tesla', 'Bentley', 'Jeep', 'Land', 'Kia', 'Volkswagen', 'Audi',
       'Lamborghini', 'Jaguar', 'Genesis', 'Nissan', 'Lincoln', 'Hyundai',
       'Honda', 'Lotus', 'GMC', 'Hummer', 'Acura', 'Toyota', 'McLaren',
       'Ferrari', 'Rolls-Royce', 'Rivian', 'Buick', 'Pontiac', 'Volvo',
       'Scion', 'FIAT', 'Saturn', 'Suzuki', 'Polestar', 'smart',
       'Mercury', 'Lucid', 'Saab', 'Karma', 'Bugatti', 'Maybach'],
      dtype=object)

In [29]:
print(df.columns.tolist())

['model_year', 'milage', 'engine', 'transmission', 'ext_col', 'int_col', 'accident', 'clean_title', 'price', 'brand_Acura', 'brand_Alfa', 'brand_Aston', 'brand_Audi', 'brand_BMW', 'brand_Bentley', 'brand_Bugatti', 'brand_Buick', 'brand_Cadillac', 'brand_Chevrolet', 'brand_Chrysler', 'brand_Dodge', 'brand_FIAT', 'brand_Ferrari', 'brand_Ford', 'brand_GMC', 'brand_Genesis', 'brand_Honda', 'brand_Hummer', 'brand_Hyundai', 'brand_INFINITI', 'brand_Jaguar', 'brand_Jeep', 'brand_Karma', 'brand_Kia', 'brand_Lamborghini', 'brand_Land', 'brand_Lexus', 'brand_Lincoln', 'brand_Lotus', 'brand_Lucid', 'brand_MINI', 'brand_Maserati', 'brand_Maybach', 'brand_Mazda', 'brand_McLaren', 'brand_Mercedes-Benz', 'brand_Mercury', 'brand_Mitsubishi', 'brand_Nissan', 'brand_Polestar', 'brand_Pontiac', 'brand_Porsche', 'brand_RAM', 'brand_Rivian', 'brand_Rolls-Royce', 'brand_Saab', 'brand_Saturn', 'brand_Scion', 'brand_Subaru', 'brand_Suzuki', 'brand_Tesla', 'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo', 'brand_smart', 'model_124 Spider Abarth', 'model_128 i', 'model_135 i', 'model_135 is', 'model_1500 Big Horn', 'model_1500 Cheyenne', 'model_1500 Cheyenne Extended Cab', 'model_1500 Classic SLT', 'model_1500 Classic Tradesman', 'model_1500 Classic Warlock', 'model_1500 Laramie', 'model_1500 Limited', 'model_1500 Longhorn', 'model_1500 Rebel', 'model_1500 SLT', 'model_1500 Sport', 'model_1500 TRX', 'model_1500 Tradesman/Express', 'model_2 Launch Edition', 'model_200 C', 'model_200 Limited', 'model_228 Gran Coupe i xDrive', 'model_228 i', 'model_230 i', 'model_240SX Base', 'model_2500 Big Horn', 'model_2500 Laramie', 'model_2500 Powerwagon', 'model_2500 SLT', 'model_2500 Tradesman', 'model_300 S', 'model_300 Touring', 'model_300C Base', 'model_300C SRT8', 'model_300M Base', 'model_300ZX Base', 'model_320 i xDrive', 'model_323 Ci', 'model_325 Ci', 'model_325 i', 'model_325 xi', 'model_328 i', 'model_328 i xDrive', 'model_328 xi', 'model_330 330i xDrive', 'model_330 i', 'model_330 i xDrive', 'model_330e iPerformance', 'model_335 i', 'model_335 i xDrive', 'model_335 is', 'model_340 i', 'model_3500 Laramie', 'model_350Z Enthusiast', 'model_350Z NISMO', 'model_350Z Touring', 'model_370Z Base', 'model_370Z NISMO', 'model_370Z NISMO Tech', 'model_370Z Touring', 'model_428 Gran Coupe i xDrive', 'model_428 i', 'model_430 430i', 'model_430 Gran Coupe i xDrive', 'model_430 i', 'model_430 i xDrive', 'model_435 Gran Coupe i', 'model_435 i', 'model_435 i xDrive', 'model_440 Gran Coupe 440i xDrive', 'model_440 Gran Coupe i', 'model_440 i xDrive', 'model_488 Spider Base', 'model_4Runner 4WD', 'model_4Runner Limited', 'model_4Runner Limited Nightshade', 'model_4Runner SR5', 'model_4Runner SR5 Premium', 'model_4Runner Sport', 'model_4Runner TRD Off Road', 'model_4Runner TRD Pro', 'model_4Runner TRD Sport', 'model_4Runner Trail', 'model_4Runner Venture', 'model_4Runner Venture Special Edition', 'model_500 Lounge', 'model_500 Sport', 'model_500X Trekking Plus', 'model_525 i', 'model_528 i', 'model_528 i xDrive', 'model_530 i', 'model_530 i xDrive', 'model_530e Base', 'model_535 i', 'model_535 i xDrive', 'model_540 i', 'model_540 i xDrive', 'model_550 i xDrive', 'model_570S Base', 'model_570S Spider', 'model_640 Gran Coupe i', 'model_640 Gran Coupe i xDrive', 'model_640 i', 'model_650 Gran Coupe i', 'model_650 Gran Coupe i xDrive', 'model_650 i', 'model_718 Boxster Base', 'model_718 Boxster GTS', 'model_718 Boxster S', 'model_718 Cayman GT4', 'model_718 Spyder Base', 'model_720S Performance', 'model_740 Li', 'model_740 i', 'model_740 iL', 'model_740e xDrive iPerformance', 'model_750 Li', 'model_750 Li xDrive', 'model_750 i', 'model_750 i xDrive', 'model_750 iL', 'model_812 Superfast Base', 'model_840 Gran Coupe i xDrive', 'model_840 i xDrive', 'model_850 Turbo', 'model_86 860 Special Edition', 'model_86 Base', 'model_9-3 Aero', 'model_9-3 SE', 'model_911 Carrera', 'model_911 Carrera 4', 'model_911 Carrera 4 Cabriolet', 'model_911 Carrera 4 GTS', 'model_911 Carrera 4S', 'model_911 Carrera 4S Cabriolet', 'model_911 Carrera C2S', 'model_911 Carrera Cabriolet', 'model_911 Carrera GTS', 'model_911 Carrera S', 'model_911 Carrera S Cabriolet', 'model_911 Carrera Turbo', 'model_911 GT2 RS', 'model_911 GT3', 'model_911 GT3 RS', 'model_911 R', 'model_911 Targa 4 GTS', 'model_911 Turbo', 'model_911 Turbo Cabriolet', 'model_911 Turbo S', 'model_A-Class A 220 4MATIC', 'model_A3 2.0 TDI Premium Plus', 'model_A3 2.0T', 'model_A3 2.0T Premium', 'model_A3 2.0T Tech Premium', 'model_A4 2.0T Premium', 'model_A4 2.0T Premium Plus', 'model_A4 2.0T Premium Plus quattro', 'model_A4 2.0T Premium quattro', 'model_A4 2.0T Titanium Premium', 'model_A4 3.2 Premium Plus quattro', 'model_A5 2.0T Premium', 'model_A5 2.0T Premium Plus', 'model_A5 2.0T Prestige', 'model_A5 45 S line Premium Plus', 'model_A5 Sportback S line Premium Plus', 'model_A6 2.0T Premium Plus', 'model_A6 2.0T Sport', 'model_A6 3.0 TDI Premium Plus', 'model_A6 3.0T Premium Plus', 'model_A6 3.0T Prestige', 'model_A6 3.2 quattro', 'model_A6 45 Premium Plus', 'model_A6 55 Premium', 'model_A6 55 Premium Plus', 'model_A6 55 Prestige', 'model_A7 3.0T Premium', 'model_A7 3.0T Premium Plus', 'model_A7 3.0T Prestige', 'model_A7 55 Premium Plus', 'model_A7 Premium', 'model_A7 Premium Plus', 'model_A8 4.0', 'model_A8 4.0T', 'model_A8 L 4.0T', 'model_A8 L 55', 'model_ALPINA B7 ALPINA B7 xDrive', 'model_ALPINA B7 Base', 'model_ALPINA B7 xDrive', 'model_AMG C 43 AMG C 43 4MATIC', 'model_AMG C 43 Base', 'model_AMG C 43 Base 4MATIC', 'model_AMG C 63 Base', 'model_AMG C 63 S', 'model_AMG C AMG C 63 S', 'model_AMG CLA 45 Base 4MATIC', 'model_AMG E 53 4MATIC', 'model_AMG E 53 Base 4MATIC', 'model_AMG E 63 S 4MATIC', 'model_AMG G 63 4MATIC', 'model_AMG G 63 Base', 'model_AMG G AMG G 63 4MATIC', 'model_AMG GL AMG GL 63 4MATIC', 'model_AMG GLA 45 Base 4MATIC', 'model_AMG GLC 43 AMG GLC 43', 'model_AMG GLC 63 Base 4MATIC', 'model_AMG GLE 43 Coupe 4MATIC', 'model_AMG GLE 63 S Coupe 4MATIC', 'model_AMG GLE AMG GLE 63 S-Model 4MATIC', 'model_AMG GLS 63 4MATIC', 'model_AMG GT 53 Base', 'model_AMG GT 63 S 4-Door', 'model_AMG GT Base', 'model_AMG GT C', 'model_AMG GT R', 'model_AMG S 63 Base 4MATIC', 'model_ATS 2.5L', 'model_ATS 3.6L Luxury', 'model_Acadia Denali', 'model_Acadia SLE', 'model_Acadia SLE-1', 'model_Acadia SLE-2', 'model_Acadia SLT-1', 'model_Accent GL', 'model_Accent GLS', 'model_Accord Crosstour EX-L', 'model_Accord EX-L', 'model_Accord Hybrid Base', 'model_Accord Sport', 'model_Air Grand Touring', 'model_Air Pure', 'model_Altima 2.5 S', 'model_Altima 2.5 SL', 'model_Altima 2.5 SV', 'model_Armada Platinum', 'model_Armada SL', 'model_Arnage R', 'model_Arteon 2.0T SE', 'model_Arteon 2.0T SEL Premium R-Line', 'model_Arteon SEL R-Line', 'model_Ascent Limited 7-Passenger', 'model_Ascent Touring 7-Passenger', 'model_Atlas 3.6L SEL Premium', 'model_Atlas Cross Sport 3.6L V6 SEL Premium', 'model_Avalanche 1500 LS', 'model_Avalanche 1500 LT', 'model_Avalanche 1500 LTZ', 'model_Avalon Limited', 'model_Avalon XLE', 'model_Avalon XLS', 'model_Aventador LP700-4', 'model_Aventador LP750-4 Superveloce', 'model_Aventador S Base', 'model_Aventador SVJ Base', 'model_Aviator Luxury', 'model_Aviator Reserve AWD', 'model_BRZ Limited', 'model_BRZ Premium', 'model_Baja Base', 'model_Beetle 1.8T', 'model_Beetle 2.0T Final Edition SE', 'model_Beetle 2.0T S', 'model_Bentayga Activity Edition', 'model_Bentayga Onyx Edition', 'model_Bentayga S', 'model_Bentayga Speed', 'model_Bentayga V8', 'model_Bentayga W12 Signature', 'model_Blazer 1LT', 'model_Bolt EUV Premier', 'model_Bolt EV LT', 'model_Boxster Base', 'model_Boxster Black Edition', 'model_Boxster GTS', 'model_Boxster RS 60 Spyder', 'model_Boxster S', 'model_Bronco', 'model_Bronco Badlands', 'model_Bronco Badlands Advanced', 'model_Bronco Big Bend Advanced', 'model_Bronco Heritage Edition Advanced', 'model_Bronco Outer Banks', 'model_Bronco Outer Banks Advanced', 'model_Bronco Raptor', 'model_Bronco Sport Base', 'model_Bronco Sport Big Bend', 'model_Bronco Sport Outer Banks', 'model_Bronco Wildtrak Advanced', 'model_Bronco XLT', 'model_C-Class C 250 Sport', 'model_C-Class C 300', 'model_C-Class C 300 4MATIC', 'model_C-Class C 300 4MATIC Luxury', 'model_C-Class C 300 4MATIC Sport', 'model_C-Class C 300 Luxury', 'model_C-Class C 63 AMG', 'model_C-Class C280 4MATIC', 'model_C-Class C300 4MATIC', 'model_C-Class C55 AMG Sport', 'model_C-HR LE', 'model_C-Max Energi SE', 'model_C30 T5 Premier Plus', 'model_C40 Recharge Pure Electric Twin Ultimate', 'model_C70 T5', 'model_CC 2.0T Sport', 'model_CC Sport', 'model_CLA-Class CLA 250', 'model_CLK-Class 500 Cabriolet', 'model_CLK-Class 550', 'model_CLK-Class CLK 350', 'model_CLS 450 Base', 'model_CLS-Class CLS 400 4MATIC', 'model_CLS-Class CLS 550', 'model_CLS-Class CLS 63 AMG S-Model 4MATIC', 'model_CR-V EX', 'model_CR-V EX-L', 'model_CR-V LX', 'model_CR-V Touring', 'model_CT 200h Base', 'model_CT 200h Premium', 'model_CT4 Luxury', 'model_CT5 Premium Luxury', 'model_CT5-V Blackwing', 'model_CT6 Luxury', 'model_CT6-V 4.2L Blackwing Twin Turbo', 'model_CTS 2.0L Turbo Luxury', 'model_CTS 3.6L Premium Luxury', 'model_CTS Luxury', 'model_CTS Performance', 'model_CTS Premium', 'model_CTS-V Base', 'model_CX-30 2.5 S Select Package', 'model_CX-30 Base', 'model_CX-30 Preferred', 'model_CX-30 Premium Package', 'model_CX-30 Select', 'model_CX-5 Grand Touring', 'model_CX-5 Touring', 'model_CX-7 Grand Touring', 'model_CX-7 Sport', 'model_CX-9 Carbon Edition', 'model_CX-9 Grand Touring', 'model_CX-9 Signature', 'model_CX-9 Touring', 'model_CX-9 Touring Plus', 'model_Caliber Express', 'model_California T', 'model_Camaro 1LT', 'model_Camaro 1SS', 'model_Camaro 2LT', 'model_Camaro 2SS', 'model_Camaro Base', 'model_Camaro LT1', 'model_Camaro Z28', 'model_Camaro ZL1', 'model_Camry Hybrid Base', 'model_Camry Hybrid LE', 'model_Camry Hybrid XLE', 'model_Camry LE', 'model_Camry Solara SLE', 'model_Camry Solara SLE V6', 'model_Camry XLE', 'model_Camry XSE', 'model_Canyon Elevation Standard', 'model_Capri XR2', 'model_Caprice Classic Base', 'model_Carrera GT Base', 'model_Cascada Base', 'model_Cayenne AWD', 'model_Cayenne Base', 'model_Cayenne E-Hybrid S', 'model_Cayenne E-Hybrid S Platinum Edition', 'model_Cayenne GTS', 'model_Cayenne Platinum Edition', 'model_Cayenne S', 'model_Cayenne Turbo', 'model_Cayenne Turbo GT', 'model_Cayenne Turbo S', 'model_Cayman Base', 'model_Cayman GT4', 'model_Cayman R', 'model_Cayman S', 'model_Challenger GT', 'model_Challenger R/T', 'model_Challenger R/T Scat Pack', 'model_Challenger SE', 'model_Challenger SRT 392', 'model_Challenger SRT Demon', 'model_Challenger SRT Hellcat', 'model_Challenger SRT8', 'model_Challenger SRT8 392', 'model_Challenger SXT', 'model_Charger Base', 'model_Charger GT', 'model_Charger R/T', 'model_Charger SE', 'model_Charger SRT Hellcat', 'model_Charger SRT Hellcat Widebody', 'model_Charger SRT8', 'model_Charger Scat Pack', 'model_Cherokee Sport', 'model_Cherokee X', 'model_Civic EX', 'model_Civic LX', 'model_Civic Si', 'model_Civic Si Base', 'model_Civic Sport', 'model_Civic Type R Touring', 'model_Clubman Cooper S ALL4', 'model_Colorado LT', 'model_Colorado LT Crew Cab', 'model_Colorado Z71', 'model_Colorado ZR2', 'model_Commander Sport', 'model_Compass Latitude', 'model_Compass Limited', 'model_Compass Sport', 'model_Compass Trailhawk', 'model_Continental GT Base', 'model_Continental GT Speed', 'model_Continental GT V8', 'model_Continental GT V8 S', 'model_Continental GT W12', 'model_Continental GTC Base', 'model_Continental Reserve', 'model_Cooper Base', 'model_Cooper S Base', 'model_Cooper S Clubman Base', 'model_Corolla Hybrid LE', 'model_Corolla LE', 'model_Corolla S Plus', 'model_Corolla iM Base', 'model_Corsair Grand Touring', 'model_Corsair Reserve', 'model_Corsair Standard', 'model_Corvette Base', 'model_Corvette Grand Sport', 'model_Corvette Stingray', 'model_Corvette Stingray Z51', 'model_Corvette Stingray w/1LT', 'model_Corvette Stingray w/2LT', 'model_Corvette Stingray w/3LT', 'model_Corvette Z06', 'model_Corvette Z06 w/2LZ', 'model_Corvette ZR-1', 'model_Countryman Cooper', 'model_Countryman Cooper S', 'model_Countryman Cooper S ALL4', 'model_Coupe Cambiocorsa', 'model_Crossfire Limited', 'model_Crosstour EX-L', 'model_Crosstrek 2.0i Limited', 'model_Crosstrek 2.0i Premium', 'model_Crosstrek Premium', 'model_Cruze LS', 'model_Cruze LT', 'model_Cruze LT Automatic', 'model_Cruze LTZ', 'model_Cube 1.8 S', 'model_Cullinan', 'model_DTS Luxury', 'model_DTS Luxury II', 'model_Dakota Big Horn/Lone Star', 'model_Dakota SLT', 'model_Dakota SLT Quad Cab', 'model_Dakota Sport', 'model_Dart SE', 'model_DeVille Base', 'model_Durango GT', 'model_Durango R/T', 'model_Durango SLT', 'model_Durango SRT', 'model_Durango SRT 392', 'model_E-Class 400E', 'model_E-Class D 2.5 Turbo', 'model_E-Class E 300', 'model_E-Class E 300 4MATIC', 'model_E-Class E 350', 'model_E-Class E 350 4MATIC', 'model_E-Class E 400', 'model_E-Class E 400 4MATIC', 'model_E-Class E 450 4MATIC', 'model_E-Class E 550', 'model_E-Class E55 AMG', 'model_E-PACE 300 Sport', 'model_E-PACE S', 'model_E250 Cargo', 'model_E350 Super Duty Base', 'model_E350 Super Duty XLT', 'model_EQS 450+ Base', 'model_ES 250 Base', 'model_ES 300h Base', 'model_ES 330 Base', 'model_ES 350 Base', 'model_EV6 GT-Line', 'model_Eclipse GS', 'model_Eclipse GT', 'model_Eclipse Spyder GS', 'model_Eclipse Spyder GT', 'model_EcoSport SES', 'model_Edge SE', 'model_Edge SEL', 'model_Edge Sport', 'model_Edge Titanium', 'model_Elantra HEV Limited', 'model_Elantra N Base', 'model_Elantra SE', 'model_Element EX', 'model_Elise Base', 'model_Enclave 1XL', 'model_Enclave Avenir', 'model_Enclave Essence', 'model_Enclave Leather', 'model_Enclave Premium', 'model_Encore Preferred', 'model_Envision Essence', 'model_Envision Preferred', 'model_Eos 2.0T', 'model_Equinox 2LT', 'model_Equinox LT', 'model_Equinox Premier w/2LZ', 'model_Equus Signature', 'model_Escalade Base', 'model_Escalade ESV Base', 'model_Escalade ESV Luxury', 'model_Escalade ESV Platinum', 'model_Escalade ESV Platinum Edition', 'model_Escalade ESV Premium Luxury', 'model_Escalade ESV Premium Luxury Platinum', 'model_Escalade ESV Sport', 'model_Escalade EXT Base', 'model_Escalade Luxury', 'model_Escalade Platinum', 'model_Escalade Premium', 'model_Escalade Premium Luxury', 'model_Escalade Premium Luxury Platinum', 'model_Escalade Sport', 'model_Escalade Sport Platinum', 'model_Escape PHEV SE', 'model_Escape SE', 'model_Escape XLT', 'model_Eurovan MV', 'model_Evora 2+2', 'model_Evora 400 Base', 'model_Evora Base', 'model_Excursion Limited', 'model_Excursion Limited 4WD', 'model_Excursion Limited Ultimate', 'model_Excursion XLS', 'model_Excursion XLT 4WD', 'model_Expedition EL King Ranch', 'model_Expedition EL Limited', 'model_Expedition EL XLT', 'model_Expedition King Ranch', 'model_Expedition Limited', 'model_Expedition Max King Ranch', 'model_Expedition Max Limited', 'model_Expedition Max XLT', 'model_Expedition Platinum', 'model_Expedition Timberline', 'model_Expedition XLT', 'model_Explorer Eddie Bauer', 'model_Explorer Limited', 'model_Explorer ST', 'model_Explorer Sport', 'model_Explorer Sport Trac XLT', 'model_Explorer Timberline', 'model_Explorer XLT', 'model_Explorer sport', 'model_Express 1500 Base', 'model_Express 1500 Work Van', 'model_Express 2500 Work Van', 'model_Express 3500 Base', 'model_Express 3500 LT', 'model_F-150 FX4', 'model_F-150 Heritage XL SuperCab Flareside', 'model_F-150 Lariat', 'model_F-150 Lightning LARIAT', 'model_F-150 Limited', 'model_F-150 Platinum', 'model_F-150 Raptor', 'model_F-150 SVT Raptor', 'model_F-150 XL', 'model_F-150 XLT', 'model_F-150 XLT SuperCab', 'model_F-250 Base', 'model_F-250 King Ranch', 'model_F-250 LARIAT', 'model_F-250 Lariat', 'model_F-250 Limited', 'model_F-250 Platinum', 'model_F-250 XL', 'model_F-250 XL Crew Cab Super Duty', 'model_F-250 XL SuperCab H/D', 'model_F-250 XLT', 'model_F-250 XLT Crew Cab Super Duty', 'model_F-250 XLT SuperCab Super Duty', 'model_F-350 Lariat', 'model_F-350 Lariat Crew Cab Super Duty DRW', 'model_F-350 Lariat Super Duty Crew Cab', 'model_F-350 Platinum', 'model_F-350 XL', 'model_F-350 XLT', 'model_F-PACE 25t Premium', 'model_F-PACE 30t R-Sport', 'model_F-PACE 35t Premium', 'model_F-PACE S', 'model_F-PACE SVR', 'model_F-TYPE', 'model_F-TYPE R', 'model_F-TYPE S', 'model_F-TYPE S British Design Edition', 'model_F-TYPE V6 S', 'model_F12berlinetta Base', 'model_F430 Berlinetta', 'model_FF Base', 'model_FJ Cruiser Base', 'model_FR-S Monogram', 'model_FX37 Base', 'model_FX50 Base', 'model_Fiesta ST', 'model_Firebird Base', 'model_Firebird Trans Am', 'model_Flex Limited', 'model_Flying Spur V8', 'model_Focus RS Base', 'model_Focus SE', 'model_Focus SEL', 'model_ForTwo Pure', 'model_Forester 2.5 X', 'model_Forester 2.5 XT', 'model_Forester 2.5i Limited', 'model_Forester Base', 'model_Forester Premium', 'model_Forte GT-Line', 'model_Forte Koup EX', 'model_Forte LX', 'model_Forte LXS', 'model_Frontier SE Crew Cab', 'model_Frontier SL', 'model_Frontier SV', 'model_Fusion Energi Titanium', 'model_Fusion Hybrid Base', 'model_Fusion Hybrid SE', 'model_Fusion Hybrid SE Hybrid', 'model_Fusion Hybrid Titanium', 'model_Fusion SE', 'model_G 550 4x4 Squared Base', 'model_G-Class G 550', 'model_G-Class G 550 4MATIC', 'model_G-Class G 63 AMG', 'model_G35 Base', 'model_G35 Sport', 'model_G37 Journey', 'model_G37 x', 'model_G70 2.0T', 'model_G70 3.3T', 'model_G70 3.3T Advanced', 'model_G80 2.5T', 'model_G80 3.8', 'model_G90 3.3T Premium', 'model_G90 5.0 Ultimate', 'model_GL-Class GL 450', 'model_GL-Class GL 450 4MATIC', 'model_GL-Class GL 550', 'model_GL-Class GL 550 4MATIC', 'model_GLA 250 Base 4MATIC', 'model_GLA-Class GLA 45 AMG', 'model_GLB 250 Base 4MATIC', 'model_GLC 300 Base 4MATIC', 'model_GLC 300 GLC 300', 'model_GLE 350 Base 4MATIC', 'model_GLE 350 GLE 350', 'model_GLE 450 GLE 450', 'model_GLS 450 Base', 'model_GLS 450 Base 4MATIC', 'model_GLS 550 Base 4MATIC', 'model_GR Corolla Circuit Edition', 'model_GR86 Base', 'model_GR86 Premium', 'model_GS 350 Base', 'model_GS 350 F Sport', 'model_GT', 'model_GT-R Black Edition', 'model_GT-R Premium', 'model_GTC4Lusso T', 'model_GTI Base', 'model_GTO Base', 'model_GV70 3.5T Sport', 'model_GV80 2.5T', 'model_GX 460 Base', 'model_GX 460 Luxury', 'model_GX 460 Premium', 'model_GX 470 Base', 'model_Gallardo Base', 'model_Gallardo LP550-2', 'model_Gallardo LP560-4', 'model_Gallardo LP570-4 Superleggera', 'model_Gallardo SE', 'model_Genesis 3.8', 'model_Genesis 4.6', 'model_Genesis 5', 'model_Genesis Coupe 2.0T', 'model_Genesis Coupe 2.0T R-Spec', 'model_Genesis Coupe 3.8 Base', 'model_Genesis Coupe 3.8 Grand Touring', 'model_Genesis Coupe 3.8 Track', 'model_Ghibli Base', 'model_Ghibli S GranLusso', 'model_Ghibli S Q4', 'model_Ghibli S Q4 GranSport', 'model_Ghost Base', 'model_Gladiator Freedom', 'model_Gladiator Mojave', 'model_Gladiator Overland', 'model_Gladiator Rubicon', 'model_Gladiator Sport', 'model_Gladiator Sport S', 'model_Gladiator Willys', 'model_Golf Alltrack TSI SE', 'model_Golf Auto TSI S', 'model_Golf GTI 2.0T Autobahn', 'model_Golf GTI 2.0T S 4-Door', 'model_Golf GTI 2.0T SE 4-Door', 'model_Golf GTI 2.0T SE w/Performance Package 4-Door', 'model_Golf R 4-Door', 'model_Golf R 4-Door w/DCC & Navigation', 'model_Golf R Base', 'model_Golf SportWagen TSI S 4-Door', 'model_Golf SportWagen TSI SE', 'model_GranTurismo Base', 'model_GranTurismo MC', 'model_GranTurismo Sport', 'model_Grand Caravan R/T', 'model_Grand Caravan SE', 'model_Grand Cherokee Altitude', 'model_Grand Cherokee L Laredo', 'model_Grand Cherokee L Limited', 'model_Grand Cherokee Laredo', 'model_Grand Cherokee Limited', 'model_Grand Cherokee Summit', 'model_Grand Wagoneer Base', 'model_Grand Wagoneer Series III', 'model_Grecale Modena', 'model_H2 Base', 'model_H2 SUT', 'model_H3 Base', 'model_HUMMER EV Edition 1', 'model_Hardtop Cooper', 'model_Hardtop Cooper S', 'model_Highlander Hybrid Limited', 'model_Highlander Hybrid Limited Platinum', 'model_Highlander Hybrid 

In [32]:
import pandas as pd

df = pd.read_csv("detaset-2.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'detaset-2.csv'

In [33]:
import pandas as pd
df = pd.read_csv("dataset-2.csv")

df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,BMW,M235 i,2015,"81,000 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,White,Red,None reported,Yes,"$27,890"
1,BMW,750 i,2017,"24,650 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,Yes,"$50,000"
2,Aston,Martin V8 Vantage Base,2008,"62,378 mi.",Gasoline,380.0HP 4.3L 8 Cylinder Engine Gasoline Fuel,M/T,Red,Beige,At least 1 accident or damage reported,Yes,"$33,995"
3,INFINITI,QX80 Luxe,2022,"49,860 mi.",Gasoline,5.6L V8 32V GDI DOHC,Automatic,Black Obsidian,Graphite,At least 1 accident or damage reported,Yes,"$47,645"
4,Subaru,BRZ Premium,2023,"5,800 mi.",Gasoline,228.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,Black,None reported,Yes,"$29,990"